### ISSUE TITLE
Lambda on Localstack never called

### ISSUE THREAD

**Issue by ShedPlant** [djfdyuruiry/lambda-alb#25]
I am trying to use this project for the first time. I need some help investigating why it isn't yet working.
When I send a request to the alb I can see it log something, but the localstack lambda never gets executed and the request times out. I suspect there's a networking problem but I don't know.

`docker-compose.yml`:
```
version: '3.8'

services:

  localstack:
    privileged: true
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - LOCALSTACK_SERVICES=lambda
      - LOCALSTACK_HOSTNAME=localstack
      - DEFAULT_REGION=eu-west-1

  alb-mock:
    image: djfdyuruiry/lambda-alb
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/tests/acceptance/alb-mock/config.json:/etc/lambda-alb/config.json
```

`tests/acceptance/alb-mock/config.json`:
```json
{
    "region": "eu-west-1",
    "lambdaEndpoint": "http://localstack:4566",
    "targets": {
        "some-lambda": {
            "lambdaName": "some-lambda-name"
        }
    }
}
```

`docker-compose up`

My lambda handler taken from https://awslabs.github.io/aws-lambda-powertools-python/latest/core/event_handler/api_gateway/ :

```python
from aws_lambda_powertools import Logger, Tracer
from aws_lambda_powertools.event_handler import ALBResolver

logger = Logger()
tracer = Tracer()
app = ALBResolver()

@app.get("some-lambda")
@tracer.capture_method
def hello_universe():
    return {"message": "hello universe"}

@logger.inject_lambda_context
@tracer.capture_lambda_handler
def lambda_handler(event, context):
    logger.info(event)
    return app.resolve(event, context)
```

Run this script to deploy a lambda to localstack:

```python
    import boto3
    localstack_url = f"http://127.0.0.1:4566"
    lambda_client = boto3.client("lambda", endpoint_url=localstack_url)

    # zip already created either manually or in other script, irrelevant for this issue
    with open(_ZIP_FILENAME, "rb") as f:
        zipped_code = f.read()

    function_name = "some-lambda-name"
    lambda_client.create_function(
        FunctionName=function_name,
        Runtime="python3.9",
        Role="not_applicable",
        Handler="myproject.some_lambda.lambda_handler.lambda_handler",
        Code={"ZipFile": zipped_code},
        PackageType="Zip",
        Publish=True,
    )
```

My test to try to call the lambda via the mock ALB:

```python
def test_alb_lambda():
    url = "http://127.0.0.1:8080/some-lambda"
    response = requests.get(url, timeout=5)
    assert response.ok
    response_json = response.json()
    print(response_json)
```

From `docker-compose logs` I can see my request reaches the ALB:
```
alb-mock_1            | 2022-04-01T11:54:54.386Z lambda-alb - Mapping express request to AWS model
alb-mock_1            | 2022-04-01T11:54:54.388Z lambda-alb - Invoking AWS Lambda 'some-lambda-name'. Path: /
```

But I **don't** see anything logged for `localstack_1`. My test fails with timeout.
